# Generated by Django 5.2.17 on 2026-09-14 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=64, unique=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Gateway-side transaction/session identifier.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('gateway', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Awaiting gateway'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='initiated', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='payments_pa_order_i_ed562a_idx'), models.Index(fields=['gateway', 'status'], name='payments_pa_gateway_186290_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('transaction_id', ''), _negated=True), fields=('transaction_id', 'gateway'), name='unique_txn_id_per_gateway')],
            },
        ),
    ]
