# Generated by Django 5.2.17 on 2026-09-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('simulated', 'Demo gateway'), ('stripe', 'Stripe'), ('razorpay', 'Razorpay')], default='simulated', max_length=30),
        ),
    ]
